// What Split says, in the 21 languages of the app (Plan §84). English is the source. The plugin's
// name is never written here: it comes from the manifest through the `{app}` hole. Amounts are
// formatted with `Intl` before they fill a hole. The `sum*` texts make up 📤's summary, said by
// whoever sends it ("I paid", "you owe me"), in their language.

export const STRINGS = {
  en: {
    title: "Shared expenses",
    close: "Close",
    back: "Back",
    forTwo: "For two people: you and the other person in a conversation.",
    newAccount: "New account",
    namePlaceholder: "Name, e.g. Lisbon trip",
    currency: "Currency",
    untitled: "Untitled account",
    empty: "No accounts yet",
    shared: "Shared",
    delete: "Delete",
    confirmDelete: "Delete “{name}” from this phone? The other person keeps their copy.",
    cancel: "Cancel",
    rename: "Rename",
    save: "Save",
    amount: "Amount",
    what: "What for, e.g. Dinner",
    add: "Add the expense",
    badAmount: "Write an amount like {example}.",
    iPaid: "I paid",
    otherPaid: "The other person paid",
    nickPaid: "{name} paid",
    half: "½ Half each",
    allForMe: "All for me",
    allForOther: "All for the other person",
    allForNick: "All for {name}",
    edit: "Edit",
    remove: "Remove",
    noExpenses: "No expenses yet",
    owesYou: "Owes you {amount}",
    youOwe: "You owe {amount}",
    even: "All square ✅",
    crowded: "⚠️ This account has entries from more than two people, so {app} can't tell who owes whom.",
    total: "Total spent: {amount}",
    settle: "💸 Settle up",
    settleTheyPay: "Record that the other person paid you {amount}?",
    settleYouPay: "Record that you paid the other person {amount}?",
    settled: "💸 Settled up",
    nick: "Your nickname, seen by the other person",
    send: "Put the summary in the chat",
    live: "Live",
    stopLive: "Stop live",
    waiting: "🔄 Waiting for the other person…",
    joined: "🔄 Live: you are both on this account",
    silent: "👤 The other person doesn't have {app} open in this conversation. They may not have it, may not have allowed it, or may have it closed.",
    unreachable: "📵 The other phone can't be reached right now.",
    left: "👋 The other person closed the account.",
    outdated: "📦 The other person has a newer {app}. Update {app} to share the account.",
    kept: "Your changes stay on this phone and join theirs when you both have the account open in this conversation.",
    liveHint: "🔄 Live joins your changes only while you both have this account open in this conversation.",
    needsChat: "To share it, open {app} from a conversation and allow it to go live.",
    joinPrompt: "📥 The other person opened “{name}”",
    join: "Join",
    notNow: "Not now",
    received: "Shared account",
    waitingData: "🔄 Waiting for the account from the other phone…",
    full: "📵 No room left on this phone: the latest changes are not saved. Delete an account to make room.",
    readOnly: "📦 This account comes from a newer {app}: update it to edit.",
    sumTotal: "total {amount}",
    sumMine: "I paid {amount}",
    sumTheirs: "you {amount}",
    sumOwesMe: "you owe me {amount}",
    sumIOwe: "I owe you {amount}",
    sumEven: "we're even ✅",
  },
  es: {
    title: "Gastos compartidos",
    close: "Cerrar",
    back: "Atrás",
    forTwo: "Para dos personas: tú y la otra persona de una conversación.",
    newAccount: "Cuenta nueva",
    namePlaceholder: "Nombre, p. ej. Viaje a Lisboa",
    currency: "Moneda",
    untitled: "Cuenta sin nombre",
    empty: "Todavía no hay cuentas",
    shared: "Compartida",
    delete: "Borrar",
    confirmDelete: "¿Borrar «{name}» de este teléfono? La otra persona conserva su copia.",
    cancel: "Cancelar",
    rename: "Renombrar",
    save: "Guardar",
    amount: "Importe",
    what: "Concepto, p. ej. Cena",
    add: "Añadir el gasto",
    badAmount: "Escribe un importe como {example}.",
    iPaid: "Pagué yo",
    otherPaid: "Pagó la otra persona",
    nickPaid: "Pagó {name}",
    half: "½ A medias",
    allForMe: "Todo mío",
    allForOther: "Todo de la otra persona",
    allForNick: "Todo de {name}",
    edit: "Editar",
    remove: "Quitar",
    noExpenses: "Todavía no hay gastos",
    owesYou: "Te debe {amount}",
    youOwe: "Le debes {amount}",
    even: "En paz ✅",
    crowded: "⚠️ Esta cuenta tiene apuntes de más de dos personas, así que {app} no puede saber quién debe a quién.",
    total: "Total gastado: {amount}",
    settle: "💸 Saldar",
    settleTheyPay: "¿Apuntar que la otra persona te pagó {amount}?",
    settleYouPay: "¿Apuntar que pagaste {amount} a la otra persona?",
    settled: "💸 Saldado",
    nick: "Tu apodo, lo ve la otra persona",
    send: "Poner el resumen en el chat",
    live: "En directo",
    stopLive: "Parar el directo",
    waiting: "🔄 Esperando a la otra persona…",
    joined: "🔄 En directo: estáis los dos en esta cuenta",
    silent: "👤 La otra persona no tiene {app} abierto en esta conversación. Puede que no lo tenga, que no le haya dado permiso o que lo tenga cerrado.",
    unreachable: "📵 Ahora no se puede llegar al otro teléfono.",
    left: "👋 La otra persona cerró la cuenta.",
    outdated: "📦 La otra persona tiene un {app} más nuevo. Actualiza {app} para compartir la cuenta.",
    kept: "Tus cambios se quedan en este teléfono y se juntan con los suyos cuando los dos tengáis la cuenta abierta en esta conversación.",
    liveHint: "🔄 El directo junta vuestros cambios solo mientras los dos tengáis esta cuenta abierta en esta conversación.",
    needsChat: "Para compartirla, abre {app} desde una conversación, con el directo permitido.",
    joinPrompt: "📥 La otra persona abrió «{name}»",
    join: "Unirse",
    notNow: "Ahora no",
    received: "Cuenta compartida",
    waitingData: "🔄 Esperando la cuenta del otro teléfono…",
    full: "📵 No queda sitio en este teléfono: los últimos cambios no se han guardado. Borra una cuenta para hacer sitio.",
    readOnly: "📦 Esta cuenta viene de un {app} más nuevo: actualízalo para editarla.",
    sumTotal: "total {amount}",
    sumMine: "yo pagué {amount}",
    sumTheirs: "tú {amount}",
    sumOwesMe: "me debes {amount}",
    sumIOwe: "te debo {amount}",
    sumEven: "estamos en paz ✅",
  },
  fr: {
    title: "Dépenses partagées",
    close: "Fermer",
    back: "Retour",
    forTwo: "Pour deux personnes : vous et l’autre personne d’une conversation.",
    newAccount: "Nouveau compte",
    namePlaceholder: "Nom, p. ex. Voyage à Lisbonne",
    currency: "Devise",
    untitled: "Compte sans nom",
    empty: "Aucun compte pour l’instant",
    shared: "Partagé",
    delete: "Supprimer",
    confirmDelete: "Supprimer « {name} » de ce téléphone ? L’autre personne garde sa copie.",
    cancel: "Annuler",
    rename: "Renommer",
    save: "Enregistrer",
    amount: "Montant",
    what: "Pour quoi, p. ex. Dîner",
    add: "Ajouter la dépense",
    badAmount: "Écrivez un montant comme {example}.",
    iPaid: "J’ai payé",
    otherPaid: "L’autre personne a payé",
    nickPaid: "{name} a payé",
    half: "½ Moitié chacun",
    allForMe: "Tout pour moi",
    allForOther: "Tout pour l’autre personne",
    allForNick: "Tout pour {name}",
    edit: "Modifier",
    remove: "Retirer",
    noExpenses: "Aucune dépense pour l’instant",
    owesYou: "L’autre personne vous doit {amount}",
    youOwe: "Vous devez {amount} à l’autre personne",
    even: "Quittes ✅",
    crowded: "⚠️ Ce compte contient des dépenses de plus de deux personnes : {app} ne peut pas savoir qui doit quoi à qui.",
    total: "Total dépensé : {amount}",
    settle: "💸 Régler",
    settleTheyPay: "Noter que l’autre personne vous a payé {amount} ?",
    settleYouPay: "Noter que vous avez payé {amount} à l’autre personne ?",
    settled: "💸 Réglé",
    nick: "Votre surnom, visible par l’autre personne",
    send: "Mettre le résumé dans la discussion",
    live: "En direct",
    stopLive: "Arrêter le direct",
    waiting: "🔄 En attente de l’autre personne…",
    joined: "🔄 En direct : vous êtes tous les deux sur ce compte",
    silent: "👤 L’autre personne n’a pas {app} ouvert dans cette conversation. Elle ne l’a peut-être pas, ne l’a peut-être pas autorisé, ou l’a peut-être fermé.",
    unreachable: "📵 L’autre téléphone est injoignable pour le moment.",
    left: "👋 L’autre personne a fermé le compte.",
    outdated: "📦 L’autre personne a une version plus récente de {app}. Mettez {app} à jour pour partager le compte.",
    kept: "Vos modifications restent sur ce téléphone et rejoignent les siennes quand vous avez tous les deux le compte ouvert dans cette conversation.",
    liveHint: "🔄 Le direct réunit vos modifications seulement tant que vous avez tous les deux ce compte ouvert dans cette conversation.",
    needsChat: "Pour le partager, ouvrez {app} depuis une conversation, avec le direct autorisé.",
    joinPrompt: "📥 L’autre personne a ouvert « {name} »",
    join: "Rejoindre",
    notNow: "Plus tard",
    received: "Compte partagé",
    waitingData: "🔄 En attente du compte de l’autre téléphone…",
    full: "📵 Plus de place sur ce téléphone : les dernières modifications ne sont pas enregistrées. Supprimez un compte pour faire de la place.",
    readOnly: "📦 Ce compte vient d’une version plus récente de {app} : mettez-le à jour pour le modifier.",
    sumTotal: "total {amount}",
    sumMine: "j’ai payé {amount}",
    sumTheirs: "toi {amount}",
    sumOwesMe: "tu me dois {amount}",
    sumIOwe: "je te dois {amount}",
    sumEven: "on est quittes ✅",
  },
  de: {
    title: "Geteilte Ausgaben",
    close: "Schließen",
    back: "Zurück",
    forTwo: "Für zwei Personen: dich und die andere Person einer Unterhaltung.",
    newAccount: "Neue Abrechnung",
    namePlaceholder: "Name, z. B. Lissabon-Reise",
    currency: "Währung",
    untitled: "Abrechnung ohne Namen",
    empty: "Noch keine Abrechnungen",
    shared: "Geteilt",
    delete: "Löschen",
    confirmDelete: "„{name}“ von diesem Telefon löschen? Die andere Person behält ihre Kopie.",
    cancel: "Abbrechen",
    rename: "Umbenennen",
    save: "Speichern",
    amount: "Betrag",
    what: "Wofür, z. B. Abendessen",
    add: "Ausgabe hinzufügen",
    badAmount: "Schreibe einen Betrag wie {example}.",
    iPaid: "Ich habe bezahlt",
    otherPaid: "Die andere Person hat bezahlt",
    nickPaid: "{name} hat bezahlt",
    half: "½ Halbe-halbe",
    allForMe: "Alles für mich",
    allForOther: "Alles für die andere Person",
    allForNick: "Alles für {name}",
    edit: "Bearbeiten",
    remove: "Entfernen",
    noExpenses: "Noch keine Ausgaben",
    owesYou: "Die andere Person schuldet dir {amount}",
    youOwe: "Du schuldest der anderen Person {amount}",
    even: "Quitt ✅",
    crowded: "⚠️ Diese Abrechnung enthält Einträge von mehr als zwei Personen, daher kann {app} nicht sagen, wer wem etwas schuldet.",
    total: "Insgesamt ausgegeben: {amount}",
    settle: "💸 Ausgleichen",
    settleTheyPay: "Eintragen, dass die andere Person dir {amount} bezahlt hat?",
    settleYouPay: "Eintragen, dass du der anderen Person {amount} bezahlt hast?",
    settled: "💸 Ausgeglichen",
    nick: "Dein Spitzname, für die andere Person sichtbar",
    send: "Zusammenfassung in den Chat stellen",
    live: "Live",
    stopLive: "Live beenden",
    waiting: "🔄 Warten auf die andere Person…",
    joined: "🔄 Live: ihr seid beide in dieser Abrechnung",
    silent: "👤 Die andere Person hat {app} in dieser Unterhaltung nicht geöffnet. Vielleicht hat sie es nicht, hat es nicht erlaubt oder hat es geschlossen.",
    unreachable: "📵 Das andere Telefon ist gerade nicht erreichbar.",
    left: "👋 Die andere Person hat die Abrechnung geschlossen.",
    outdated: "📦 Die andere Person hat ein neueres {app}. Aktualisiere {app}, um die Abrechnung zu teilen.",
    kept: "Deine Änderungen bleiben auf diesem Telefon und kommen mit ihren zusammen, wenn ihr beide die Abrechnung in dieser Unterhaltung geöffnet habt.",
    liveHint: "🔄 Live führt eure Änderungen nur zusammen, solange ihr beide diese Abrechnung in dieser Unterhaltung geöffnet habt.",
    needsChat: "Um sie zu teilen, öffne {app} aus einer Unterhaltung, mit erlaubtem Live-Modus.",
    joinPrompt: "📥 Die andere Person hat „{name}“ geöffnet",
    join: "Beitreten",
    notNow: "Nicht jetzt",
    received: "Geteilte Abrechnung",
    waitingData: "🔄 Warten auf die Abrechnung vom anderen Telefon…",
    full: "📵 Kein Platz mehr auf diesem Telefon: Die letzten Änderungen sind nicht gespeichert. Lösche eine Abrechnung, um Platz zu schaffen.",
    readOnly: "📦 Diese Abrechnung stammt aus einem neueren {app}: Aktualisiere es, um sie zu bearbeiten.",
    sumTotal: "insgesamt {amount}",
    sumMine: "ich habe {amount} bezahlt",
    sumTheirs: "du {amount}",
    sumOwesMe: "du schuldest mir {amount}",
    sumIOwe: "ich schulde dir {amount}",
    sumEven: "wir sind quitt ✅",
  },
  it: {
    title: "Spese condivise",
    close: "Chiudi",
    back: "Indietro",
    forTwo: "Per due persone: tu e l’altra persona di una conversazione.",
    newAccount: "Nuovo conto",
    namePlaceholder: "Nome, ad es. Viaggio a Lisbona",
    currency: "Valuta",
    untitled: "Conto senza nome",
    empty: "Ancora nessun conto",
    shared: "Condiviso",
    delete: "Elimina",
    confirmDelete: "Eliminare «{name}» da questo telefono? L’altra persona conserva la sua copia.",
    cancel: "Annulla",
    rename: "Rinomina",
    save: "Salva",
    amount: "Importo",
    what: "Per cosa, ad es. Cena",
    add: "Aggiungi la spesa",
    badAmount: "Scrivi un importo come {example}.",
    iPaid: "Ho pagato io",
    otherPaid: "Ha pagato l’altra persona",
    nickPaid: "Ha pagato {name}",
    half: "½ Metà ciascuno",
    allForMe: "Tutto per me",
    allForOther: "Tutto per l’altra persona",
    allForNick: "Tutto per {name}",
    edit: "Modifica",
    remove: "Rimuovi",
    noExpenses: "Ancora nessuna spesa",
    owesYou: "L’altra persona ti deve {amount}",
    youOwe: "Devi {amount} all’altra persona",
    even: "Pari ✅",
    crowded: "⚠️ Questo conto ha voci di più di due persone, quindi {app} non può dire chi deve a chi.",
    total: "Totale speso: {amount}",
    settle: "💸 Salda",
    settleTheyPay: "Segnare che l’altra persona ti ha pagato {amount}?",
    settleYouPay: "Segnare che hai pagato {amount} all’altra persona?",
    settled: "💸 Saldato",
    nick: "Il tuo soprannome, visibile all’altra persona",
    send: "Metti il riepilogo nella chat",
    live: "In diretta",
    stopLive: "Ferma la diretta",
    waiting: "🔄 In attesa dell’altra persona…",
    joined: "🔄 In diretta: siete entrambi su questo conto",
    silent: "👤 L’altra persona non ha {app} aperto in questa conversazione. Forse non ce l’ha, non l’ha autorizzato o l’ha chiuso.",
    unreachable: "📵 L’altro telefono non è raggiungibile in questo momento.",
    left: "👋 L’altra persona ha chiuso il conto.",
    outdated: "📦 L’altra persona ha una versione più recente di {app}. Aggiorna {app} per condividere il conto.",
    kept: "Le tue modifiche restano su questo telefono e si uniscono alle sue quando avete entrambi il conto aperto in questa conversazione.",
    liveHint: "🔄 La diretta unisce le vostre modifiche solo mentre avete entrambi questo conto aperto in questa conversazione.",
    needsChat: "Per condividerlo, apri {app} da una conversazione, con la diretta consentita.",
    joinPrompt: "📥 L’altra persona ha aperto «{name}»",
    join: "Unisciti",
    notNow: "Non ora",
    received: "Conto condiviso",
    waitingData: "🔄 In attesa del conto dall’altro telefono…",
    full: "📵 Non c’è più spazio su questo telefono: le ultime modifiche non sono salvate. Elimina un conto per fare spazio.",
    readOnly: "📦 Questo conto viene da una versione più recente di {app}: aggiornalo per modificarlo.",
    sumTotal: "totale {amount}",
    sumMine: "io ho pagato {amount}",
    sumTheirs: "tu {amount}",
    sumOwesMe: "mi devi {amount}",
    sumIOwe: "ti devo {amount}",
    sumEven: "siamo pari ✅",
  },
  pt: {
    title: "Despesas partilhadas",
    close: "Fechar",
    back: "Voltar",
    forTwo: "Para duas pessoas: você e a outra pessoa de uma conversa.",
    newAccount: "Nova conta",
    namePlaceholder: "Nome, p. ex. Viagem a Lisboa",
    currency: "Moeda",
    untitled: "Conta sem nome",
    empty: "Ainda não há contas",
    shared: "Partilhada",
    delete: "Apagar",
    confirmDelete: "Apagar «{name}» deste telemóvel? A outra pessoa fica com a sua cópia.",
    cancel: "Cancelar",
    rename: "Mudar o nome",
    save: "Guardar",
    amount: "Valor",
    what: "Para quê, p. ex. Jantar",
    add: "Adicionar a despesa",
    badAmount: "Escreva um valor como {example}.",
    iPaid: "Paguei eu",
    otherPaid: "Pagou a outra pessoa",
    nickPaid: "Pagou {name}",
    half: "½ A meias",
    allForMe: "Tudo para mim",
    allForOther: "Tudo para a outra pessoa",
    allForNick: "Tudo para {name}",
    edit: "Editar",
    remove: "Remover",
    noExpenses: "Ainda não há despesas",
    owesYou: "A outra pessoa deve-lhe {amount}",
    youOwe: "Deve {amount} à outra pessoa",
    even: "Contas certas ✅",
    crowded: "⚠️ Esta conta tem registos de mais de duas pessoas, por isso o {app} não consegue saber quem deve a quem.",
    total: "Total gasto: {amount}",
    settle: "💸 Acertar contas",
    settleTheyPay: "Registar que a outra pessoa lhe pagou {amount}?",
    settleYouPay: "Registar que pagou {amount} à outra pessoa?",
    settled: "💸 Contas acertadas",
    nick: "A sua alcunha, que a outra pessoa vê",
    send: "Pôr o resumo na conversa",
    live: "Em direto",
    stopLive: "Parar o direto",
    waiting: "🔄 À espera da outra pessoa…",
    joined: "🔄 Em direto: estão os dois nesta conta",
    silent: "👤 A outra pessoa não tem o {app} aberto nesta conversa. Pode não o ter, não lhe ter dado permissão ou tê-lo fechado.",
    unreachable: "📵 Agora não é possível chegar ao outro telemóvel.",
    left: "👋 A outra pessoa fechou a conta.",
    outdated: "📦 A outra pessoa tem um {app} mais recente. Atualize o {app} para partilharem a conta.",
    kept: "As suas alterações ficam neste telemóvel e juntam-se às da outra pessoa quando os dois tiverem a conta aberta nesta conversa.",
    liveHint: "🔄 O direto junta as vossas alterações só enquanto os dois tiverem esta conta aberta nesta conversa.",
    needsChat: "Para a partilhar, abra o {app} a partir de uma conversa, com o direto permitido.",
    joinPrompt: "📥 A outra pessoa abriu «{name}»",
    join: "Entrar",
    notNow: "Agora não",
    received: "Conta partilhada",
    waitingData: "🔄 À espera da conta do outro telemóvel…",
    full: "📵 Não há espaço neste telemóvel: as últimas alterações não foram guardadas. Apague uma conta para libertar espaço.",
    readOnly: "📦 Esta conta vem de um {app} mais recente: atualize-o para a editar.",
    sumTotal: "total {amount}",
    sumMine: "eu paguei {amount}",
    sumTheirs: "tu {amount}",
    sumOwesMe: "deves-me {amount}",
    sumIOwe: "devo-te {amount}",
    sumEven: "estamos quites ✅",
  },
  ro: {
    title: "Cheltuieli comune",
    close: "Închide",
    back: "Înapoi",
    forTwo: "Pentru două persoane: tu și cealaltă persoană dintr-o conversație.",
    newAccount: "Cont nou",
    namePlaceholder: "Nume, de ex. Excursie la Lisabona",
    currency: "Monedă",
    untitled: "Cont fără nume",
    empty: "Încă nu există conturi",
    shared: "Partajat",
    delete: "Șterge",
    confirmDelete: "Ștergi „{name}” de pe acest telefon? Cealaltă persoană își păstrează copia.",
    cancel: "Anulează",
    rename: "Redenumește",
    save: "Salvează",
    amount: "Sumă",
    what: "Pentru ce, de ex. Cină",
    add: "Adaugă cheltuiala",
    badAmount: "Scrie o sumă ca {example}.",
    iPaid: "Am plătit eu",
    otherPaid: "A plătit cealaltă persoană",
    nickPaid: "A plătit {name}",
    half: "½ Jumătate fiecare",
    allForMe: "Tot pentru mine",
    allForOther: "Tot pentru cealaltă persoană",
    allForNick: "Tot pentru {name}",
    edit: "Editează",
    remove: "Elimină",
    noExpenses: "Încă nu există cheltuieli",
    owesYou: "Cealaltă persoană îți datorează {amount}",
    youOwe: "Îi datorezi celeilalte persoane {amount}",
    even: "Chit ✅",
    crowded: "⚠️ Acest cont are înregistrări de la mai mult de două persoane, așa că {app} nu poate spune cine cui datorează.",
    total: "Total cheltuit: {amount}",
    settle: "💸 Achită",
    settleTheyPay: "Notezi că cealaltă persoană ți-a plătit {amount}?",
    settleYouPay: "Notezi că i-ai plătit celeilalte persoane {amount}?",
    settled: "💸 Achitat",
    nick: "Porecla ta, văzută de cealaltă persoană",
    send: "Pune rezumatul în chat",
    live: "În direct",
    stopLive: "Oprește modul în direct",
    waiting: "🔄 Se așteaptă cealaltă persoană…",
    joined: "🔄 În direct: sunteți amândoi în acest cont",
    silent: "👤 Cealaltă persoană nu are {app} deschis în această conversație. Poate nu îl are, nu i-a dat permisiunea sau l-a închis.",
    unreachable: "📵 Celălalt telefon nu poate fi contactat acum.",
    left: "👋 Cealaltă persoană a închis contul.",
    outdated: "📦 Cealaltă persoană are o versiune mai nouă de {app}. Actualizează {app} ca să partajați contul.",
    kept: "Modificările tale rămân pe acest telefon și se unesc cu ale ei când aveți amândoi contul deschis în această conversație.",
    liveHint: "🔄 Modul în direct vă unește modificările doar cât timp aveți amândoi acest cont deschis în această conversație.",
    needsChat: "Ca să-l partajezi, deschide {app} dintr-o conversație, cu modul în direct permis.",
    joinPrompt: "📥 Cealaltă persoană a deschis „{name}”",
    join: "Alătură-te",
    notNow: "Nu acum",
    received: "Cont partajat",
    waitingData: "🔄 Se așteaptă contul de pe celălalt telefon…",
    full: "📵 Nu mai e loc pe acest telefon: ultimele modificări nu sunt salvate. Șterge un cont ca să faci loc.",
    readOnly: "📦 Acest cont vine dintr-o versiune mai nouă de {app}: actualizează-l ca să-l editezi.",
    sumTotal: "total {amount}",
    sumMine: "eu am plătit {amount}",
    sumTheirs: "tu {amount}",
    sumOwesMe: "îmi datorezi {amount}",
    sumIOwe: "îți datorez {amount}",
    sumEven: "suntem chit ✅",
  },
  pl: {
    title: "Wspólne wydatki",
    close: "Zamknij",
    back: "Wstecz",
    forTwo: "Dla dwóch osób: ciebie i drugiej osoby z rozmowy.",
    newAccount: "Nowe rozliczenie",
    namePlaceholder: "Nazwa, np. Wyjazd do Lizbony",
    currency: "Waluta",
    untitled: "Rozliczenie bez nazwy",
    empty: "Nie ma jeszcze rozliczeń",
    shared: "Udostępnione",
    delete: "Usuń",
    confirmDelete: "Usunąć „{name}” z tego telefonu? Druga osoba zachowa swoją kopię.",
    cancel: "Anuluj",
    rename: "Zmień nazwę",
    save: "Zapisz",
    amount: "Kwota",
    what: "Za co, np. Kolacja",
    add: "Dodaj wydatek",
    badAmount: "Wpisz kwotę, np. {example}.",
    iPaid: "Zapłacone przeze mnie",
    otherPaid: "Zapłacone przez drugą osobę",
    nickPaid: "Zapłacone przez: {name}",
    half: "½ Po połowie",
    allForMe: "Wszystko dla mnie",
    allForOther: "Wszystko dla drugiej osoby",
    allForNick: "Wszystko dla: {name}",
    edit: "Edytuj",
    remove: "Usuń pozycję",
    noExpenses: "Nie ma jeszcze wydatków",
    owesYou: "Należy ci się {amount}",
    youOwe: "Do oddania: {amount}",
    even: "Wszystko rozliczone ✅",
    crowded: "⚠️ To rozliczenie ma wpisy od więcej niż dwóch osób, więc {app} nie może ustalić, kto komu ile oddaje.",
    total: "Wydano łącznie: {amount}",
    settle: "💸 Rozlicz",
    settleTheyPay: "Zapisać, że druga osoba oddała ci {amount}?",
    settleYouPay: "Zapisać, że oddajesz drugiej osobie {amount}?",
    settled: "💸 Rozliczone",
    nick: "Twój pseudonim, widoczny dla drugiej osoby",
    send: "Wstaw podsumowanie do czatu",
    live: "Na żywo",
    stopLive: "Zakończ tryb na żywo",
    waiting: "🔄 Czekanie na drugą osobę…",
    joined: "🔄 Na żywo: oboje jesteście w tym rozliczeniu",
    silent: "👤 Druga osoba nie ma otwartej aplikacji {app} w tej rozmowie. Może jej nie mieć, mogła nie dać zgody albo ją zamknęła.",
    unreachable: "📵 Nie można teraz połączyć się z drugim telefonem.",
    left: "👋 Druga osoba zamknęła rozliczenie.",
    outdated: "📦 Druga osoba ma nowszą wersję {app}. Zaktualizuj {app}, aby prowadzić rozliczenie razem.",
    kept: "Twoje zmiany zostają na tym telefonie i połączą się z jej zmianami, gdy oboje będziecie mieć rozliczenie otwarte w tej rozmowie.",
    liveHint: "🔄 Tryb na żywo łączy wasze zmiany tylko wtedy, gdy oboje macie to rozliczenie otwarte w tej rozmowie.",
    needsChat: "Aby je udostępnić, otwórz {app} z rozmowy, z dozwolonym trybem na żywo.",
    joinPrompt: "📥 Druga osoba otworzyła „{name}”",
    join: "Dołącz",
    notNow: "Nie teraz",
    received: "Udostępnione rozliczenie",
    waitingData: "🔄 Czekanie na rozliczenie z drugiego telefonu…",
    full: "📵 Brak miejsca na tym telefonie: ostatnie zmiany nie są zapisane. Usuń rozliczenie, aby zrobić miejsce.",
    readOnly: "📦 To rozliczenie pochodzi z nowszej wersji {app}: zaktualizuj ją, aby edytować.",
    sumTotal: "razem {amount}",
    sumMine: "ode mnie {amount}",
    sumTheirs: "od ciebie {amount}",
    sumOwesMe: "oddajesz mi {amount}",
    sumIOwe: "oddaję ci {amount}",
    sumEven: "jesteśmy kwita ✅",
  },
  ru: {
    title: "Общие расходы",
    close: "Закрыть",
    back: "Назад",
    forTwo: "Для двоих: вас и другого человека из переписки.",
    newAccount: "Новый счёт",
    namePlaceholder: "Название, например Поездка в Лиссабон",
    currency: "Валюта",
    untitled: "Счёт без названия",
    empty: "Счетов пока нет",
    shared: "Общий",
    delete: "Удалить",
    confirmDelete: "Удалить «{name}» с этого телефона? У другого человека останется его копия.",
    cancel: "Отмена",
    rename: "Переименовать",
    save: "Сохранить",
    amount: "Сумма",
    what: "За что, например Ужин",
    add: "Добавить расход",
    badAmount: "Введите сумму, например {example}.",
    iPaid: "Оплачено мной",
    otherPaid: "Оплачено другим человеком",
    nickPaid: "Оплачено: {name}",
    half: "½ Пополам",
    allForMe: "Целиком для меня",
    allForOther: "Целиком для другого человека",
    allForNick: "Целиком для: {name}",
    edit: "Изменить",
    remove: "Убрать",
    noExpenses: "Расходов пока нет",
    owesYou: "Вам должны {amount}",
    youOwe: "Вы должны {amount}",
    even: "В расчёте ✅",
    crowded: "⚠️ В этом счёте есть записи больше чем двух человек, поэтому {app} не может сказать, кто кому должен.",
    total: "Всего потрачено: {amount}",
    settle: "💸 Рассчитаться",
    settleTheyPay: "Записать, что другой человек вернул вам {amount}?",
    settleYouPay: "Записать, что вы вернули другому человеку {amount}?",
    settled: "💸 Рассчитались",
    nick: "Ваше имя для другого человека",
    send: "Вставить итог в чат",
    live: "Вместе",
    stopLive: "Закончить совместную работу",
    waiting: "🔄 Ждём другого человека…",
    joined: "🔄 Вместе: вы оба в этом счёте",
    silent: "👤 У другого человека не открыт {app} в этой переписке. Возможно, у него его нет, он не дал разрешение или закрыл его.",
    unreachable: "📵 Сейчас до другого телефона не достучаться.",
    left: "👋 Другой человек закрыл счёт.",
    outdated: "📦 У другого человека более новая версия {app}. Обновите {app}, чтобы вести счёт вместе.",
    kept: "Ваши изменения остаются на этом телефоне и объединятся с его изменениями, когда у вас обоих будет открыт счёт в этой переписке.",
    liveHint: "🔄 Изменения объединяются, только пока у вас обоих открыт этот счёт в этой переписке.",
    needsChat: "Чтобы вести счёт вместе, откройте {app} из переписки и разрешите ему совместную работу.",
    joinPrompt: "📥 Другой человек открыл «{name}»",
    join: "Присоединиться",
    notNow: "Не сейчас",
    received: "Общий счёт",
    waitingData: "🔄 Ждём счёт с другого телефона…",
    full: "📵 На этом телефоне не осталось места: последние изменения не сохранены. Удалите счёт, чтобы освободить место.",
    readOnly: "📦 Этот счёт из более новой версии {app}: обновите его, чтобы редактировать.",
    sumTotal: "всего {amount}",
    sumMine: "я заплатил(а) {amount}",
    sumTheirs: "ты {amount}",
    sumOwesMe: "ты мне должен(на) {amount}",
    sumIOwe: "я тебе должен(на) {amount}",
    sumEven: "мы в расчёте ✅",
  },
  uk: {
    title: "Спільні витрати",
    close: "Закрити",
    back: "Назад",
    forTwo: "Для двох: вас та іншої людини з розмови.",
    newAccount: "Новий рахунок",
    namePlaceholder: "Назва, наприклад Поїздка до Лісабона",
    currency: "Валюта",
    untitled: "Рахунок без назви",
    empty: "Рахунків ще немає",
    shared: "Спільний",
    delete: "Видалити",
    confirmDelete: "Видалити «{name}» з цього телефона? У іншої людини залишиться її копія.",
    cancel: "Скасувати",
    rename: "Перейменувати",
    save: "Зберегти",
    amount: "Сума",
    what: "За що, наприклад Вечеря",
    add: "Додати витрату",
    badAmount: "Введіть суму, наприклад {example}.",
    iPaid: "Оплачено мною",
    otherPaid: "Оплачено іншою людиною",
    nickPaid: "Оплачено: {name}",
    half: "½ Навпіл",
    allForMe: "Повністю для мене",
    allForOther: "Повністю для іншої людини",
    allForNick: "Повністю для: {name}",
    edit: "Змінити",
    remove: "Прибрати",
    noExpenses: "Витрат ще немає",
    owesYou: "Вам винні {amount}",
    youOwe: "Ви винні {amount}",
    even: "Розраховано ✅",
    crowded: "⚠️ У цьому рахунку є записи більше ніж двох людей, тому {app} не може сказати, хто кому винен.",
    total: "Усього витрачено: {amount}",
    settle: "💸 Розрахуватися",
    settleTheyPay: "Записати, що інша людина повернула вам {amount}?",
    settleYouPay: "Записати, що ви повернули іншій людині {amount}?",
    settled: "💸 Розрахувалися",
    nick: "Ваше ім’я для іншої людини",
    send: "Вставити підсумок у чат",
    live: "Разом",
    stopLive: "Завершити спільну роботу",
    waiting: "🔄 Чекаємо на іншу людину…",
    joined: "🔄 Разом: ви обоє в цьому рахунку",
    silent: "👤 Інша людина не має відкритого {app} у цій розмові. Можливо, у неї його немає, вона не дала дозволу або закрила його.",
    unreachable: "📵 Зараз до іншого телефона не можна достукатися.",
    left: "👋 Інша людина закрила рахунок.",
    outdated: "📦 Інша людина має новішу версію {app}. Оновіть {app}, щоб вести рахунок разом.",
    kept: "Ваші зміни залишаються на цьому телефоні й об’єднаються з її змінами, коли у вас обох буде відкритий рахунок у цій розмові.",
    liveHint: "🔄 Зміни об’єднуються, лише поки у вас обох відкритий цей рахунок у цій розмові.",
    needsChat: "Щоб вести рахунок разом, відкрийте {app} з розмови й дозвольте йому спільну роботу.",
    joinPrompt: "📥 Інша людина відкрила «{name}»",
    join: "Приєднатися",
    notNow: "Не зараз",
    received: "Спільний рахунок",
    waitingData: "🔄 Чекаємо на рахунок з іншого телефона…",
    full: "📵 На цьому телефоні не залишилося місця: останні зміни не збережено. Видаліть рахунок, щоб звільнити місце.",
    readOnly: "📦 Цей рахунок із новішої версії {app}: оновіть його, щоб редагувати.",
    sumTotal: "усього {amount}",
    sumMine: "я заплатив(-ла) {amount}",
    sumTheirs: "ти {amount}",
    sumOwesMe: "ти мені винен(-на) {amount}",
    sumIOwe: "я тобі винен(-на) {amount}",
    sumEven: "ми квити ✅",
  },
  tr: {
    title: "Ortak harcamalar",
    close: "Kapat",
    back: "Geri",
    forTwo: "İki kişi için: siz ve bir sohbetteki diğer kişi.",
    newAccount: "Yeni hesap",
    namePlaceholder: "Ad, ör. Lizbon gezisi",
    currency: "Para birimi",
    untitled: "Adsız hesap",
    empty: "Henüz hesap yok",
    shared: "Paylaşılan",
    delete: "Sil",
    confirmDelete: "“{name}” bu telefondan silinsin mi? Diğer kişi kendi kopyasını saklar.",
    cancel: "İptal",
    rename: "Yeniden adlandır",
    save: "Kaydet",
    amount: "Tutar",
    what: "Ne için, ör. Akşam yemeği",
    add: "Harcamayı ekle",
    badAmount: "{example} gibi bir tutar yazın.",
    iPaid: "Ben ödedim",
    otherPaid: "Diğer kişi ödedi",
    nickPaid: "{name} ödedi",
    half: "½ Yarı yarıya",
    allForMe: "Hepsi benim",
    allForOther: "Hepsi diğer kişinin",
    allForNick: "Hepsi {name} için",
    edit: "Düzenle",
    remove: "Kaldır",
    noExpenses: "Henüz harcama yok",
    owesYou: "Diğer kişi size {amount} borçlu",
    youOwe: "Diğer kişiye {amount} borçlusunuz",
    even: "Ödeşildi ✅",
    crowded: "⚠️ Bu hesapta ikiden fazla kişinin kayıtları var, bu yüzden {app} kimin kime borçlu olduğunu söyleyemez.",
    total: "Toplam harcama: {amount}",
    settle: "💸 Hesaplaş",
    settleTheyPay: "Diğer kişinin size {amount} ödediği kaydedilsin mi?",
    settleYouPay: "Diğer kişiye {amount} ödediğiniz kaydedilsin mi?",
    settled: "💸 Hesaplaşıldı",
    nick: "Takma adınız, diğer kişi görür",
    send: "Özeti sohbete koy",
    live: "Canlı",
    stopLive: "Canlıyı durdur",
    waiting: "🔄 Diğer kişi bekleniyor…",
    joined: "🔄 Canlı: ikiniz de bu hesaptasınız",
    silent: "👤 Diğer kişide bu sohbette {app} açık değil. Onda olmayabilir, izin vermemiş olabilir ya da kapatmış olabilir.",
    unreachable: "📵 Diğer telefona şu anda ulaşılamıyor.",
    left: "👋 Diğer kişi hesabı kapattı.",
    outdated: "📦 Diğer kişide daha yeni bir {app} var. Hesabı paylaşmak için {app} uygulamasını güncelleyin.",
    kept: "Değişiklikleriniz bu telefonda kalır ve ikiniz de hesabı bu sohbette açtığınızda onunkilerle birleşir.",
    liveHint: "🔄 Canlı mod değişikliklerinizi yalnızca ikiniz de bu hesabı bu sohbette açık tuttuğunuz sürece birleştirir.",
    needsChat: "Paylaşmak için {app} uygulamasını bir sohbetten açın ve canlı moda izin verin.",
    joinPrompt: "📥 Diğer kişi “{name}” hesabını açtı",
    join: "Katıl",
    notNow: "Şimdi değil",
    received: "Paylaşılan hesap",
    waitingData: "🔄 Hesap diğer telefondan bekleniyor…",
    full: "📵 Bu telefonda yer kalmadı: son değişiklikler kaydedilmedi. Yer açmak için bir hesap silin.",
    readOnly: "📦 Bu hesap daha yeni bir {app} sürümünden geliyor: düzenlemek için güncelleyin.",
    sumTotal: "toplam {amount}",
    sumMine: "ben {amount} ödedim",
    sumTheirs: "sen {amount}",
    sumOwesMe: "bana {amount} borçlusun",
    sumIOwe: "sana {amount} borçluyum",
    sumEven: "ödeştik ✅",
  },
  ar: {
    title: "مصاريف مشتركة",
    close: "إغلاق",
    back: "رجوع",
    forTwo: "لشخصين: أنت والشخص الآخر في محادثة.",
    newAccount: "حساب جديد",
    namePlaceholder: "الاسم، مثل رحلة لشبونة",
    currency: "العملة",
    untitled: "حساب بلا اسم",
    empty: "لا توجد حسابات بعد",
    shared: "مشترك",
    delete: "حذف",
    confirmDelete: "حذف «{name}» من هذا الهاتف؟ يحتفظ الشخص الآخر بنسخته.",
    cancel: "إلغاء",
    rename: "إعادة التسمية",
    save: "حفظ",
    amount: "المبلغ",
    what: "مقابل ماذا، مثل العشاء",
    add: "إضافة المصروف",
    badAmount: "اكتب مبلغًا مثل {example}.",
    iPaid: "أنا دفعت",
    otherPaid: "الشخص الآخر دفع",
    nickPaid: "{name} دفع",
    half: "½ مناصفة",
    allForMe: "كله عليّ",
    allForOther: "كله على الشخص الآخر",
    allForNick: "كله على {name}",
    edit: "تعديل",
    remove: "إزالة",
    noExpenses: "لا توجد مصاريف بعد",
    owesYou: "الشخص الآخر مدين لك بـ {amount}",
    youOwe: "أنت مدين للشخص الآخر بـ {amount}",
    even: "لا ديون بينكما ✅",
    crowded: "⚠️ في هذا الحساب قيود من أكثر من شخصين، لذا لا يستطيع {app} معرفة من المدين لمن.",
    total: "إجمالي المصروف: {amount}",
    settle: "💸 تسوية",
    settleTheyPay: "تسجيل أن الشخص الآخر دفع لك {amount}؟",
    settleYouPay: "تسجيل أنك دفعت للشخص الآخر {amount}؟",
    settled: "💸 تمت التسوية",
    nick: "لقبك، يراه الشخص الآخر",
    send: "وضع الملخص في الدردشة",
    live: "مباشر",
    stopLive: "إيقاف المباشر",
    waiting: "🔄 بانتظار الشخص الآخر…",
    joined: "🔄 مباشر: أنتما الاثنان في هذا الحساب",
    silent: "👤 ليس لدى الشخص الآخر {app} مفتوحًا في هذه المحادثة. ربما لا يملكه، أو لم يمنحه الإذن، أو أغلقه.",
    unreachable: "📵 لا يمكن الوصول إلى الهاتف الآخر الآن.",
    left: "👋 أغلق الشخص الآخر الحساب.",
    outdated: "📦 لدى الشخص الآخر إصدار أحدث من {app}. حدّث {app} لتتشاركا الحساب.",
    kept: "تبقى تغييراتك على هذا الهاتف وتنضم إلى تغييراته عندما يكون الحساب مفتوحًا لديكما في هذه المحادثة.",
    liveHint: "🔄 يجمع الوضع المباشر تغييراتكما فقط ما دام هذا الحساب مفتوحًا لديكما في هذه المحادثة.",
    needsChat: "لمشاركته، افتح {app} من محادثة مع السماح له بالوضع المباشر.",
    joinPrompt: "📥 فتح الشخص الآخر «{name}»",
    join: "انضمام",
    notNow: "ليس الآن",
    received: "حساب مشترك",
    waitingData: "🔄 بانتظار الحساب من الهاتف الآخر…",
    full: "📵 لا توجد مساحة كافية على هذا الهاتف: لم تُحفظ آخر التغييرات. احذف حسابًا لإفساح المجال.",
    readOnly: "📦 هذا الحساب من إصدار أحدث من {app}: حدّثه لتعديله.",
    sumTotal: "المجموع {amount}",
    sumMine: "دفعتُ {amount}",
    sumTheirs: "أنت {amount}",
    sumOwesMe: "أنت مدين لي بـ {amount}",
    sumIOwe: "أنا مدين لك بـ {amount}",
    sumEven: "لا ديون بيننا ✅",
  },
  hi: {
    title: "साझा खर्च",
    close: "बंद करें",
    back: "वापस",
    forTwo: "दो लोगों के लिए: आप और किसी बातचीत का दूसरा व्यक्ति।",
    newAccount: "नया हिसाब",
    namePlaceholder: "नाम, जैसे लिस्बन यात्रा",
    currency: "मुद्रा",
    untitled: "बिना नाम का हिसाब",
    empty: "अभी कोई हिसाब नहीं",
    shared: "साझा",
    delete: "मिटाएँ",
    confirmDelete: "“{name}” इस फ़ोन से मिटाएँ? दूसरे व्यक्ति के पास उनकी कॉपी रहेगी।",
    cancel: "रद्द करें",
    rename: "नाम बदलें",
    save: "सहेजें",
    amount: "रकम",
    what: "किस लिए, जैसे खाना",
    add: "खर्च जोड़ें",
    badAmount: "{example} जैसी रकम लिखें।",
    iPaid: "मैंने दिए",
    otherPaid: "दूसरे व्यक्ति ने दिए",
    nickPaid: "{name} ने दिए",
    half: "½ आधा-आधा",
    allForMe: "पूरा मेरा",
    allForOther: "पूरा दूसरे व्यक्ति का",
    allForNick: "पूरा {name} का",
    edit: "बदलें",
    remove: "हटाएँ",
    noExpenses: "अभी कोई खर्च नहीं",
    owesYou: "आपको {amount} मिलने हैं",
    youOwe: "आपको {amount} देने हैं",
    even: "हिसाब बराबर ✅",
    crowded: "⚠️ इस हिसाब में दो से ज़्यादा लोगों की एंट्री हैं, इसलिए {app} नहीं बता सकता कि किसे किसको कितना देना है।",
    total: "कुल खर्च: {amount}",
    settle: "💸 हिसाब चुकाएँ",
    settleTheyPay: "दर्ज करें कि दूसरे व्यक्ति ने आपको {amount} दिए?",
    settleYouPay: "दर्ज करें कि आपने दूसरे व्यक्ति को {amount} दिए?",
    settled: "💸 हिसाब चुकता",
    nick: "आपका उपनाम, दूसरा व्यक्ति इसे देखता है",
    send: "सारांश चैट में डालें",
    live: "लाइव",
    stopLive: "लाइव बंद करें",
    waiting: "🔄 दूसरे व्यक्ति का इंतज़ार…",
    joined: "🔄 लाइव: आप दोनों इस हिसाब में हैं",
    silent: "👤 दूसरे व्यक्ति के पास इस बातचीत में {app} खुला नहीं है। हो सकता है उनके पास यह न हो, उन्होंने अनुमति न दी हो, या इसे बंद कर दिया हो।",
    unreachable: "📵 अभी दूसरे फ़ोन तक नहीं पहुँचा जा सकता।",
    left: "👋 दूसरे व्यक्ति ने हिसाब बंद कर दिया।",
    outdated: "📦 दूसरे व्यक्ति के पास {app} का नया संस्करण है। हिसाब साझा करने के लिए {app} अपडेट करें।",
    kept: "आपके बदलाव इस फ़ोन पर रहते हैं और जब आप दोनों इस बातचीत में हिसाब खोलेंगे, तब उनके बदलावों से मिल जाएँगे।",
    liveHint: "🔄 लाइव आपके बदलाव तभी मिलाता है जब आप दोनों ने इस बातचीत में यह हिसाब खोल रखा हो।",
    needsChat: "इसे साझा करने के लिए {app} को किसी बातचीत से खोलें और उसे लाइव की अनुमति दें।",
    joinPrompt: "📥 दूसरे व्यक्ति ने “{name}” खोला",
    join: "जुड़ें",
    notNow: "अभी नहीं",
    received: "साझा हिसाब",
    waitingData: "🔄 दूसरे फ़ोन से हिसाब का इंतज़ार…",
    full: "📵 इस फ़ोन पर जगह नहीं बची: आख़िरी बदलाव सहेजे नहीं गए। जगह बनाने के लिए कोई हिसाब मिटाएँ।",
    readOnly: "📦 यह हिसाब {app} के नए संस्करण से है: इसे बदलने के लिए अपडेट करें।",
    sumTotal: "कुल {amount}",
    sumMine: "मैंने {amount} दिए",
    sumTheirs: "तुमने {amount}",
    sumOwesMe: "तुम्हें मुझे {amount} देने हैं",
    sumIOwe: "मुझे तुम्हें {amount} देने हैं",
    sumEven: "हिसाब बराबर ✅",
  },
  bn: {
    title: "যৌথ খরচ",
    close: "বন্ধ",
    back: "পিছনে",
    forTwo: "দুজনের জন্য: আপনি আর কোনো কথোপকথনের অন্যজন।",
    newAccount: "নতুন হিসাব",
    namePlaceholder: "নাম, যেমন লিসবন ভ্রমণ",
    currency: "মুদ্রা",
    untitled: "নামহীন হিসাব",
    empty: "এখনও কোনো হিসাব নেই",
    shared: "শেয়ার করা",
    delete: "মুছুন",
    confirmDelete: "এই ফোন থেকে “{name}” মুছবেন? অন্যজনের কাছে তার কপি থাকবে।",
    cancel: "বাতিল",
    rename: "নাম বদলান",
    save: "সংরক্ষণ",
    amount: "পরিমাণ",
    what: "কীসের জন্য, যেমন রাতের খাবার",
    add: "খরচ যোগ করুন",
    badAmount: "{example} এর মতো একটি পরিমাণ লিখুন।",
    iPaid: "আমি দিয়েছি",
    otherPaid: "অন্যজন দিয়েছেন",
    nickPaid: "{name} দিয়েছেন",
    half: "½ অর্ধেক-অর্ধেক",
    allForMe: "পুরোটা আমার",
    allForOther: "পুরোটা অন্যজনের",
    allForNick: "পুরোটা {name}-এর",
    edit: "সম্পাদনা",
    remove: "সরান",
    noExpenses: "এখনও কোনো খরচ নেই",
    owesYou: "আপনি {amount} পাবেন",
    youOwe: "আপনাকে {amount} দিতে হবে",
    even: "হিসাব সমান ✅",
    crowded: "⚠️ এই হিসাবে দুজনের বেশি মানুষের এন্ট্রি আছে, তাই {app} বলতে পারে না কে কাকে কত দেবে।",
    total: "মোট খরচ: {amount}",
    settle: "💸 হিসাব মেটান",
    settleTheyPay: "লিখে রাখবেন যে অন্যজন আপনাকে {amount} দিয়েছেন?",
    settleYouPay: "লিখে রাখবেন যে আপনি অন্যজনকে {amount} দিয়েছেন?",
    settled: "💸 হিসাব মিটেছে",
    nick: "আপনার ডাকনাম, অন্যজন এটি দেখেন",
    send: "সারাংশ চ্যাটে দিন",
    live: "লাইভ",
    stopLive: "লাইভ বন্ধ করুন",
    waiting: "🔄 অন্যজনের জন্য অপেক্ষা…",
    joined: "🔄 লাইভ: আপনারা দুজনেই এই হিসাবে আছেন",
    silent: "👤 অন্যজনের এই কথোপকথনে {app} খোলা নেই। হয়তো তার কাছে এটি নেই, অনুমতি দেননি, বা বন্ধ করে রেখেছেন।",
    unreachable: "📵 এখন অন্য ফোনে পৌঁছানো যাচ্ছে না।",
    left: "👋 অন্যজন হিসাবটি বন্ধ করেছেন।",
    outdated: "📦 অন্যজনের কাছে {app}-এর নতুন সংস্করণ আছে। হিসাব শেয়ার করতে {app} আপডেট করুন।",
    kept: "আপনার পরিবর্তন এই ফোনে থাকে এবং আপনারা দুজনেই এই কথোপকথনে হিসাবটি খুললে তার পরিবর্তনের সাথে মিলে যায়।",
    liveHint: "🔄 লাইভ আপনাদের পরিবর্তন শুধু তখনই মেলায় যখন দুজনেই এই কথোপকথনে হিসাবটি খুলে রাখেন।",
    needsChat: "শেয়ার করতে কোনো কথোপকথন থেকে {app} খুলুন এবং লাইভের অনুমতি দিন।",
    joinPrompt: "📥 অন্যজন “{name}” খুলেছেন",
    join: "যোগ দিন",
    notNow: "এখন নয়",
    received: "শেয়ার করা হিসাব",
    waitingData: "🔄 অন্য ফোন থেকে হিসাবের অপেক্ষা…",
    full: "📵 এই ফোনে আর জায়গা নেই: শেষ পরিবর্তনগুলো সংরক্ষিত হয়নি। জায়গা করতে একটি হিসাব মুছুন।",
    readOnly: "📦 এই হিসাবটি {app}-এর নতুন সংস্করণ থেকে এসেছে: সম্পাদনা করতে আপডেট করুন।",
    sumTotal: "মোট {amount}",
    sumMine: "আমি দিয়েছি {amount}",
    sumTheirs: "তুমি {amount}",
    sumOwesMe: "তুমি আমাকে {amount} দেবে",
    sumIOwe: "আমি তোমাকে {amount} দেব",
    sumEven: "আমরা সমান ✅",
  },
  id: {
    title: "Biaya bersama",
    close: "Tutup",
    back: "Kembali",
    forTwo: "Untuk dua orang: Anda dan orang lain dalam sebuah percakapan.",
    newAccount: "Catatan baru",
    namePlaceholder: "Nama, mis. Liburan ke Lisboa",
    currency: "Mata uang",
    untitled: "Catatan tanpa nama",
    empty: "Belum ada catatan",
    shared: "Dibagikan",
    delete: "Hapus",
    confirmDelete: "Hapus “{name}” dari ponsel ini? Orang lain tetap menyimpan salinannya.",
    cancel: "Batal",
    rename: "Ganti nama",
    save: "Simpan",
    amount: "Jumlah",
    what: "Untuk apa, mis. Makan malam",
    add: "Tambahkan biaya",
    badAmount: "Tulis jumlah seperti {example}.",
    iPaid: "Saya yang bayar",
    otherPaid: "Orang lain yang bayar",
    nickPaid: "{name} yang bayar",
    half: "½ Bagi dua",
    allForMe: "Semua untuk saya",
    allForOther: "Semua untuk orang lain",
    allForNick: "Semua untuk {name}",
    edit: "Ubah",
    remove: "Buang",
    noExpenses: "Belum ada biaya",
    owesYou: "Orang lain berutang {amount} kepada Anda",
    youOwe: "Anda berutang {amount} kepada orang lain",
    even: "Impas ✅",
    crowded: "⚠️ Catatan ini berisi biaya dari lebih dari dua orang, jadi {app} tidak bisa tahu siapa berutang kepada siapa.",
    total: "Total biaya: {amount}",
    settle: "💸 Lunasi",
    settleTheyPay: "Catat bahwa orang lain membayar Anda {amount}?",
    settleYouPay: "Catat bahwa Anda membayar orang lain {amount}?",
    settled: "💸 Lunas",
    nick: "Nama panggilan Anda, terlihat oleh orang lain",
    send: "Taruh ringkasan di obrolan",
    live: "Langsung",
    stopLive: "Hentikan mode langsung",
    waiting: "🔄 Menunggu orang lain…",
    joined: "🔄 Langsung: kalian berdua ada di catatan ini",
    silent: "👤 Orang lain tidak membuka {app} di percakapan ini. Mungkin dia tidak memilikinya, tidak memberi izin, atau sudah menutupnya.",
    unreachable: "📵 Ponsel lain tidak dapat dijangkau sekarang.",
    left: "👋 Orang lain menutup catatan.",
    outdated: "📦 Orang lain punya {app} versi lebih baru. Perbarui {app} untuk berbagi catatan.",
    kept: "Perubahan Anda tetap di ponsel ini dan bergabung dengan perubahannya saat kalian berdua membuka catatan di percakapan ini.",
    liveHint: "🔄 Mode langsung menggabungkan perubahan kalian hanya selama kalian berdua membuka catatan ini di percakapan ini.",
    needsChat: "Untuk membagikannya, buka {app} dari sebuah percakapan dan izinkan mode langsung.",
    joinPrompt: "📥 Orang lain membuka “{name}”",
    join: "Gabung",
    notNow: "Nanti",
    received: "Catatan bersama",
    waitingData: "🔄 Menunggu catatan dari ponsel lain…",
    full: "📵 Ruang di ponsel ini habis: perubahan terakhir belum tersimpan. Hapus sebuah catatan untuk memberi ruang.",
    readOnly: "📦 Catatan ini berasal dari {app} versi lebih baru: perbarui untuk mengeditnya.",
    sumTotal: "total {amount}",
    sumMine: "aku bayar {amount}",
    sumTheirs: "kamu {amount}",
    sumOwesMe: "kamu utang {amount} ke aku",
    sumIOwe: "aku utang {amount} ke kamu",
    sumEven: "kita impas ✅",
  },
  vi: {
    title: "Chi tiêu chung",
    close: "Đóng",
    back: "Quay lại",
    forTwo: "Dành cho hai người: bạn và người kia trong một cuộc trò chuyện.",
    newAccount: "Sổ mới",
    namePlaceholder: "Tên, ví dụ Chuyến đi Lisbon",
    currency: "Tiền tệ",
    untitled: "Sổ chưa đặt tên",
    empty: "Chưa có sổ nào",
    shared: "Đã chia sẻ",
    delete: "Xóa",
    confirmDelete: "Xóa “{name}” khỏi điện thoại này? Người kia vẫn giữ bản của họ.",
    cancel: "Hủy",
    rename: "Đổi tên",
    save: "Lưu",
    amount: "Số tiền",
    what: "Cho việc gì, ví dụ Bữa tối",
    add: "Thêm khoản chi",
    badAmount: "Hãy viết số tiền như {example}.",
    iPaid: "Tôi trả",
    otherPaid: "Người kia trả",
    nickPaid: "{name} trả",
    half: "½ Chia đôi",
    allForMe: "Tất cả của tôi",
    allForOther: "Tất cả của người kia",
    allForNick: "Tất cả của {name}",
    edit: "Sửa",
    remove: "Bỏ",
    noExpenses: "Chưa có khoản chi nào",
    owesYou: "Người kia nợ bạn {amount}",
    youOwe: "Bạn nợ người kia {amount}",
    even: "Đã sòng phẳng ✅",
    crowded: "⚠️ Sổ này có khoản ghi của hơn hai người, nên {app} không thể biết ai nợ ai.",
    total: "Tổng chi: {amount}",
    settle: "💸 Thanh toán",
    settleTheyPay: "Ghi lại rằng người kia đã trả bạn {amount}?",
    settleYouPay: "Ghi lại rằng bạn đã trả người kia {amount}?",
    settled: "💸 Đã thanh toán",
    nick: "Biệt danh của bạn, người kia sẽ thấy",
    send: "Đưa bản tóm tắt vào cuộc trò chuyện",
    live: "Trực tiếp",
    stopLive: "Dừng trực tiếp",
    waiting: "🔄 Đang chờ người kia…",
    joined: "🔄 Trực tiếp: cả hai đang ở sổ này",
    silent: "👤 Người kia chưa mở {app} trong cuộc trò chuyện này. Có thể họ không có, chưa cho phép, hoặc đã đóng nó.",
    unreachable: "📵 Hiện không liên lạc được với điện thoại kia.",
    left: "👋 Người kia đã đóng sổ.",
    outdated: "📦 Người kia có {app} mới hơn. Hãy cập nhật {app} để cùng dùng sổ.",
    kept: "Thay đổi của bạn vẫn ở trên điện thoại này và sẽ gộp với của họ khi cả hai cùng mở sổ trong cuộc trò chuyện này.",
    liveHint: "🔄 Chế độ trực tiếp chỉ gộp thay đổi khi cả hai đang mở sổ này trong cuộc trò chuyện này.",
    needsChat: "Để chia sẻ, hãy mở {app} từ một cuộc trò chuyện và cho phép chế độ trực tiếp.",
    joinPrompt: "📥 Người kia đã mở “{name}”",
    join: "Tham gia",
    notNow: "Để sau",
    received: "Sổ chung",
    waitingData: "🔄 Đang chờ sổ từ điện thoại kia…",
    full: "📵 Điện thoại này hết chỗ: các thay đổi mới nhất chưa được lưu. Hãy xóa một sổ để có chỗ.",
    readOnly: "📦 Sổ này đến từ {app} mới hơn: hãy cập nhật để chỉnh sửa.",
    sumTotal: "tổng {amount}",
    sumMine: "mình trả {amount}",
    sumTheirs: "bạn {amount}",
    sumOwesMe: "bạn nợ mình {amount}",
    sumIOwe: "mình nợ bạn {amount}",
    sumEven: "mình hòa nhau rồi ✅",
  },
  th: {
    title: "ค่าใช้จ่ายร่วม",
    close: "ปิด",
    back: "กลับ",
    forTwo: "สำหรับสองคน: คุณและอีกฝ่ายในการสนทนา",
    newAccount: "บัญชีใหม่",
    namePlaceholder: "ชื่อ เช่น ทริปลิสบอน",
    currency: "สกุลเงิน",
    untitled: "บัญชีไม่มีชื่อ",
    empty: "ยังไม่มีบัญชี",
    shared: "แชร์แล้ว",
    delete: "ลบ",
    confirmDelete: "ลบ “{name}” ออกจากโทรศัพท์นี้? อีกฝ่ายยังมีสำเนาของตัวเอง",
    cancel: "ยกเลิก",
    rename: "เปลี่ยนชื่อ",
    save: "บันทึก",
    amount: "จำนวนเงิน",
    what: "ค่าอะไร เช่น อาหารเย็น",
    add: "เพิ่มค่าใช้จ่าย",
    badAmount: "เขียนจำนวนเงินแบบ {example}",
    iPaid: "ฉันจ่าย",
    otherPaid: "อีกฝ่ายจ่าย",
    nickPaid: "{name} จ่าย",
    half: "½ หารครึ่ง",
    allForMe: "ของฉันทั้งหมด",
    allForOther: "ของอีกฝ่ายทั้งหมด",
    allForNick: "ของ {name} ทั้งหมด",
    edit: "แก้ไข",
    remove: "เอาออก",
    noExpenses: "ยังไม่มีค่าใช้จ่าย",
    owesYou: "อีกฝ่ายติดคุณ {amount}",
    youOwe: "คุณติดอีกฝ่าย {amount}",
    even: "เคลียร์กันแล้ว ✅",
    crowded: "⚠️ บัญชีนี้มีรายการจากมากกว่าสองคน {app} จึงบอกไม่ได้ว่าใครติดใคร",
    total: "ใช้ไปทั้งหมด: {amount}",
    settle: "💸 เคลียร์ยอด",
    settleTheyPay: "บันทึกว่าอีกฝ่ายจ่ายคุณ {amount}?",
    settleYouPay: "บันทึกว่าคุณจ่ายอีกฝ่าย {amount}?",
    settled: "💸 เคลียร์ยอดแล้ว",
    nick: "ชื่อเล่นของคุณ อีกฝ่ายจะเห็น",
    send: "ใส่สรุปลงในแชท",
    live: "เรียลไทม์",
    stopLive: "หยุดเรียลไทม์",
    waiting: "🔄 กำลังรออีกฝ่าย…",
    joined: "🔄 เรียลไทม์: ทั้งสองอยู่ในบัญชีนี้",
    silent: "👤 อีกฝ่ายไม่ได้เปิด {app} ในการสนทนานี้ อาจไม่มีแอปนี้ ไม่ได้อนุญาต หรือปิดไปแล้ว",
    unreachable: "📵 ตอนนี้ติดต่อโทรศัพท์อีกเครื่องไม่ได้",
    left: "👋 อีกฝ่ายปิดบัญชีแล้ว",
    outdated: "📦 อีกฝ่ายมี {app} เวอร์ชันใหม่กว่า อัปเดต {app} เพื่อใช้บัญชีร่วมกัน",
    kept: "การเปลี่ยนแปลงของคุณอยู่ในโทรศัพท์นี้ และจะรวมกับของอีกฝ่ายเมื่อทั้งสองเปิดบัญชีในการสนทนานี้",
    liveHint: "🔄 โหมดเรียลไทม์รวมการเปลี่ยนแปลงเฉพาะตอนที่ทั้งสองเปิดบัญชีนี้ในการสนทนานี้",
    needsChat: "หากต้องการแชร์ ให้เปิด {app} จากการสนทนาและอนุญาตโหมดเรียลไทม์",
    joinPrompt: "📥 อีกฝ่ายเปิด “{name}”",
    join: "เข้าร่วม",
    notNow: "ไว้ทีหลัง",
    received: "บัญชีที่แชร์",
    waitingData: "🔄 กำลังรอบัญชีจากโทรศัพท์อีกเครื่อง…",
    full: "📵 โทรศัพท์นี้ไม่มีที่ว่างแล้ว: การเปลี่ยนแปลงล่าสุดยังไม่ได้บันทึก ลบบัญชีหนึ่งเพื่อเพิ่มที่ว่าง",
    readOnly: "📦 บัญชีนี้มาจาก {app} เวอร์ชันใหม่กว่า: อัปเดตเพื่อแก้ไข",
    sumTotal: "รวม {amount}",
    sumMine: "ฉันจ่าย {amount}",
    sumTheirs: "เธอ {amount}",
    sumOwesMe: "เธอติดฉัน {amount}",
    sumIOwe: "ฉันติดเธอ {amount}",
    sumEven: "เราเคลียร์กันแล้ว ✅",
  },
  ja: {
    title: "割り勘",
    close: "閉じる",
    back: "戻る",
    forTwo: "二人用：あなたと会話の相手。",
    newAccount: "新しいノート",
    namePlaceholder: "名前（例：リスボン旅行）",
    currency: "通貨",
    untitled: "名前のないノート",
    empty: "ノートはまだありません",
    shared: "共有中",
    delete: "削除",
    confirmDelete: "「{name}」をこの電話から削除しますか？相手のコピーは残ります。",
    cancel: "キャンセル",
    rename: "名前を変更",
    save: "保存",
    amount: "金額",
    what: "内容（例：夕食）",
    add: "支出を追加",
    badAmount: "{example} のように金額を入力してください。",
    iPaid: "自分が払った",
    otherPaid: "相手が払った",
    nickPaid: "{name} が払った",
    half: "½ 半分ずつ",
    allForMe: "全部自分の分",
    allForOther: "全部相手の分",
    allForNick: "全部 {name} の分",
    edit: "編集",
    remove: "削除する",
    noExpenses: "支出はまだありません",
    owesYou: "相手から {amount} もらう",
    youOwe: "相手に {amount} 払う",
    even: "貸し借りなし ✅",
    crowded: "⚠️ このノートには三人以上の記録があるため、{app} は誰が誰にいくら払うか判断できません。",
    total: "合計支出：{amount}",
    settle: "💸 精算する",
    settleTheyPay: "相手から {amount} 受け取ったと記録しますか？",
    settleYouPay: "相手に {amount} 払ったと記録しますか？",
    settled: "💸 精算",
    nick: "あなたのニックネーム（相手に表示されます）",
    send: "まとめをチャットに入れる",
    live: "ライブ",
    stopLive: "ライブを終了",
    waiting: "🔄 相手を待っています…",
    joined: "🔄 ライブ：二人ともこのノートを開いています",
    silent: "👤 相手はこの会話で {app} を開いていません。持っていない、許可していない、または閉じている可能性があります。",
    unreachable: "📵 今は相手の電話に届きません。",
    left: "👋 相手がノートを閉じました。",
    outdated: "📦 相手の {app} のほうが新しいバージョンです。ノートを共有するには {app} を更新してください。",
    kept: "あなたの変更はこの電話に残り、二人ともこの会話でノートを開いたときに相手の変更とまとまります。",
    liveHint: "🔄 ライブで変更がまとまるのは、二人ともこの会話でこのノートを開いている間だけです。",
    needsChat: "共有するには、会話から {app} を開き、ライブを許可してください。",
    joinPrompt: "📥 相手が「{name}」を開きました",
    join: "参加",
    notNow: "今はしない",
    received: "共有ノート",
    waitingData: "🔄 相手の電話からノートを待っています…",
    full: "📵 この電話に空きがありません：最新の変更は保存されていません。ノートを削除して空きを作ってください。",
    readOnly: "📦 このノートは新しいバージョンの {app} で作られています：編集するには更新してください。",
    sumTotal: "合計 {amount}",
    sumMine: "私が {amount} 払った",
    sumTheirs: "あなたが {amount}",
    sumOwesMe: "あなたは私に {amount} 払う",
    sumIOwe: "私はあなたに {amount} 払う",
    sumEven: "貸し借りなし ✅",
  },
  ko: {
    title: "함께 쓴 돈",
    close: "닫기",
    back: "뒤로",
    forTwo: "두 사람용: 나와 대화 상대.",
    newAccount: "새 정산",
    namePlaceholder: "이름, 예: 리스본 여행",
    currency: "통화",
    untitled: "이름 없는 정산",
    empty: "아직 정산이 없습니다",
    shared: "공유됨",
    delete: "삭제",
    confirmDelete: "이 휴대폰에서 “{name}”을(를) 삭제할까요? 상대방은 자기 사본을 그대로 가집니다.",
    cancel: "취소",
    rename: "이름 바꾸기",
    save: "저장",
    amount: "금액",
    what: "무엇에, 예: 저녁 식사",
    add: "지출 추가",
    badAmount: "{example}처럼 금액을 입력하세요.",
    iPaid: "내가 냄",
    otherPaid: "상대방이 냄",
    nickPaid: "{name}이(가) 냄",
    half: "½ 반반",
    allForMe: "전부 내 몫",
    allForOther: "전부 상대방 몫",
    allForNick: "전부 {name} 몫",
    edit: "수정",
    remove: "빼기",
    noExpenses: "아직 지출이 없습니다",
    owesYou: "받을 돈 {amount}",
    youOwe: "줄 돈 {amount}",
    even: "주고받을 돈 없음 ✅",
    crowded: "⚠️ 이 정산에는 세 명 이상의 기록이 있어서 {app}이(가) 누가 누구에게 줘야 하는지 알 수 없습니다.",
    total: "총 지출: {amount}",
    settle: "💸 다 갚기",
    settleTheyPay: "상대방이 {amount}을(를) 갚았다고 기록할까요?",
    settleYouPay: "상대방에게 {amount}을(를) 갚았다고 기록할까요?",
    settled: "💸 다 갚음",
    nick: "내 별명 (상대방에게 보임)",
    send: "요약을 채팅에 넣기",
    live: "실시간",
    stopLive: "실시간 끝내기",
    waiting: "🔄 상대방을 기다리는 중…",
    joined: "🔄 실시간: 두 사람 모두 이 정산에 있습니다",
    silent: "👤 상대방이 이 대화에서 {app}을(를) 열지 않았습니다. 앱이 없거나, 허용하지 않았거나, 닫았을 수 있습니다.",
    unreachable: "📵 지금은 상대방 휴대폰에 연결할 수 없습니다.",
    left: "👋 상대방이 정산을 닫았습니다.",
    outdated: "📦 상대방의 {app}이(가) 더 새 버전입니다. 정산을 함께하려면 {app}을(를) 업데이트하세요.",
    kept: "변경 내용은 이 휴대폰에 남아 있다가, 두 사람 모두 이 대화에서 정산을 열면 상대방의 변경 내용과 합쳐집니다.",
    liveHint: "🔄 실시간 모드는 두 사람 모두 이 대화에서 이 정산을 열어 둔 동안에만 변경 내용을 합칩니다.",
    needsChat: "함께하려면 대화에서 {app}을(를) 열고 실시간을 허용하세요.",
    joinPrompt: "📥 상대방이 “{name}”을(를) 열었습니다",
    join: "참여",
    notNow: "나중에",
    received: "공유된 정산",
    waitingData: "🔄 상대방 휴대폰에서 정산을 기다리는 중…",
    full: "📵 이 휴대폰에 공간이 없습니다: 최근 변경 내용이 저장되지 않았습니다. 정산을 삭제해 공간을 만드세요.",
    readOnly: "📦 이 정산은 더 새 버전의 {app}에서 왔습니다: 수정하려면 업데이트하세요.",
    sumTotal: "총 {amount}",
    sumMine: "내가 {amount} 냄",
    sumTheirs: "네가 {amount}",
    sumOwesMe: "나한테 {amount} 줘야 해",
    sumIOwe: "내가 {amount} 줘야 해",
    sumEven: "우리 정산 끝 ✅",
  },
  "zh-CN": {
    title: "共同开销",
    close: "关闭",
    back: "返回",
    forTwo: "两人使用：你和对话中的对方。",
    newAccount: "新账本",
    namePlaceholder: "名称，例如 里斯本旅行",
    currency: "货币",
    untitled: "未命名账本",
    empty: "还没有账本",
    shared: "已共享",
    delete: "删除",
    confirmDelete: "要从这台手机删除“{name}”吗？对方会保留自己的副本。",
    cancel: "取消",
    rename: "重命名",
    save: "保存",
    amount: "金额",
    what: "用途，例如 晚饭",
    add: "添加开销",
    badAmount: "请输入像 {example} 这样的金额。",
    iPaid: "我付的",
    otherPaid: "对方付的",
    nickPaid: "{name} 付的",
    half: "½ 平摊",
    allForMe: "全算我的",
    allForOther: "全算对方的",
    allForNick: "全算 {name} 的",
    edit: "编辑",
    remove: "移除",
    noExpenses: "还没有开销",
    owesYou: "对方欠你 {amount}",
    youOwe: "你欠对方 {amount}",
    even: "两清 ✅",
    crowded: "⚠️ 这个账本里有两个以上的人的记录，所以 {app} 无法判断谁欠谁。",
    total: "总共花了：{amount}",
    settle: "💸 结清",
    settleTheyPay: "记录对方已付给你 {amount}？",
    settleYouPay: "记录你已付给对方 {amount}？",
    settled: "💸 已结清",
    nick: "你的昵称，对方会看到",
    send: "把摘要放进聊天",
    live: "实时",
    stopLive: "停止实时",
    waiting: "🔄 正在等待对方…",
    joined: "🔄 实时：你们俩都在这个账本里",
    silent: "👤 对方没有在这个对话中打开 {app}。对方可能没有安装、没有授权，或已经关闭。",
    unreachable: "📵 现在无法连接到对方的手机。",
    left: "👋 对方关闭了账本。",
    outdated: "📦 对方的 {app} 版本更新。请更新 {app} 以便共享账本。",
    kept: "你的更改会保留在这台手机上，等你们俩都在这个对话中打开账本时再与对方的合并。",
    liveHint: "🔄 只有你们俩都在这个对话中打开这个账本时，实时模式才会合并更改。",
    needsChat: "要共享，请从对话中打开 {app}，并允许实时功能。",
    joinPrompt: "📥 对方打开了“{name}”",
    join: "加入",
    notNow: "以后再说",
    received: "共享账本",
    waitingData: "🔄 正在等待对方手机上的账本…",
    full: "📵 这台手机没有空间了：最近的更改没有保存。删除一个账本以腾出空间。",
    readOnly: "📦 这个账本来自更新版本的 {app}：请更新后再编辑。",
    sumTotal: "总计 {amount}",
    sumMine: "我付了 {amount}",
    sumTheirs: "你 {amount}",
    sumOwesMe: "你欠我 {amount}",
    sumIOwe: "我欠你 {amount}",
    sumEven: "我们两清了 ✅",
  },
  "zh-TW": {
    title: "共同開銷",
    close: "關閉",
    back: "返回",
    forTwo: "兩人使用：你和對話中的對方。",
    newAccount: "新帳本",
    namePlaceholder: "名稱，例如 里斯本旅行",
    currency: "貨幣",
    untitled: "未命名帳本",
    empty: "還沒有帳本",
    shared: "已共享",
    delete: "刪除",
    confirmDelete: "要從這支手機刪除「{name}」嗎？對方會保留自己的副本。",
    cancel: "取消",
    rename: "重新命名",
    save: "儲存",
    amount: "金額",
    what: "用途，例如 晚餐",
    add: "新增開銷",
    badAmount: "請輸入像 {example} 這樣的金額。",
    iPaid: "我付的",
    otherPaid: "對方付的",
    nickPaid: "{name} 付的",
    half: "½ 平分",
    allForMe: "全算我的",
    allForOther: "全算對方的",
    allForNick: "全算 {name} 的",
    edit: "編輯",
    remove: "移除",
    noExpenses: "還沒有開銷",
    owesYou: "對方欠你 {amount}",
    youOwe: "你欠對方 {amount}",
    even: "兩清 ✅",
    crowded: "⚠️ 這個帳本裡有兩個以上的人的紀錄，所以 {app} 無法判斷誰欠誰。",
    total: "總共花了：{amount}",
    settle: "💸 結清",
    settleTheyPay: "記錄對方已付給你 {amount}？",
    settleYouPay: "記錄你已付給對方 {amount}？",
    settled: "💸 已結清",
    nick: "你的暱稱，對方會看到",
    send: "把摘要放進聊天",
    live: "即時",
    stopLive: "停止即時",
    waiting: "🔄 正在等待對方…",
    joined: "🔄 即時：你們都在這個帳本裡",
    silent: "👤 對方沒有在這個對話中開啟 {app}。對方可能沒有安裝、沒有授權，或已經關閉。",
    unreachable: "📵 現在無法連線到對方的手機。",
    left: "👋 對方關閉了帳本。",
    outdated: "📦 對方的 {app} 版本較新。請更新 {app} 以便共享帳本。",
    kept: "你的變更會保留在這支手機上，等你們都在這個對話中開啟帳本時再與對方的合併。",
    liveHint: "🔄 只有你們都在這個對話中開啟這個帳本時，即時模式才會合併變更。",
    needsChat: "要共享，請從對話中開啟 {app}，並允許即時功能。",
    joinPrompt: "📥 對方開啟了「{name}」",
    join: "加入",
    notNow: "稍後再說",
    received: "共享帳本",
    waitingData: "🔄 正在等待對方手機上的帳本…",
    full: "📵 這支手機沒有空間了：最近的變更沒有儲存。刪除一個帳本以騰出空間。",
    readOnly: "📦 這個帳本來自較新版本的 {app}：請更新後再編輯。",
    sumTotal: "總計 {amount}",
    sumMine: "我付了 {amount}",
    sumTheirs: "你 {amount}",
    sumOwesMe: "你欠我 {amount}",
    sumIOwe: "我欠你 {amount}",
    sumEven: "我們兩清了 ✅",
  },
};
